#!/bin/bash
# clickup-slow-setup.sh - Langsamer Aufbau mit Rate-Limit-Checks
# ClickUp Limit: 100 requests/minute

API_TOKEN=$(cat ~/.config/clickup/api_token 2>/dev/null)
SPACE_ID="90040311585"
TEAM_ID="9006104573"

if [ -z "$API_TOKEN" ]; then
    echo "❌ Kein API Token"
    exit 1
fi

echo "🐢 ClickUp Slow Setup (Rate-Limit-sicher)"
echo "========================================="
echo ""
echo "⏱️  Warte 2 Sekunden zwischen jedem Call..."
echo "🎯 Max 30 Calls/Minute (sicher unter Limit)"
echo ""

REQUEST_COUNT=0

make_request() {
    local method="$1"
    local url="$2"
    local data="$3"
    
    REQUEST_COUNT=$((REQUEST_COUNT + 1))
    echo "📡 Request #$REQUEST_COUNT"
    
    if [ -n "$data" ]; then
        curl -s -X "$method" "$url" \
            -H "Authorization: $API_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$data"
    else
        curl -s -X "$method" "$url" \
            -H "Authorization: $API_TOKEN" \
            -H "Content-Type: application/json"
    fi
    
    # Slow down - 2 seconds between requests
    sleep 2
}

echo "📋 Step 1: Prüfe API-Zugriff..."
TEST=$(curl -s "https://api.clickup.com/api/v2/team" \
    -H "Authorization: $API_TOKEN" \
    -H "Content-Type: application/json")

if echo "$TEST" | jq -e '.teams[0].id' > /dev/null 2>&1; then
    echo "✅ API Zugriff OK"
    echo "   Team: $(echo "$TEST" | jq -r '.teams[0].name')"
else
    echo "❌ API Fehler: $TEST"
    exit 1
fi

echo ""
echo "⏱️  Starte langsamen Aufbau..."
echo ""

echo ""
echo "📁 Step 2: Lade alle Folders in Delivery..."
FOLDERS=$(make_request "GET" "https://api.clickup.com/api/v2/space/$SPACE_ID/folder?archived=false")

if ! echo "$FOLDERS" | jq -e '.folders' > /dev/null 2>&1; then
    echo "❌ Konnte Folders nicht laden"
    echo "Response: $FOLDERS"
    exit 1
fi

echo "✅ Folders geladen"
echo ""

# Finde Client Folders
CLIENTS=("Green Cola Germany" "schnelleinfachgesund" "Ferro Berlin" "RAZECO" "ATB Bau")

echo "🎯 Step 3: Erstelle Creative Testing Struktur..."
echo ""

for client in "${CLIENTS[@]}"; do
    echo "📂 Client: $client"
    
    # Find folder ID
    FOLDER_ID=$(echo "$FOLDERS" | jq -r ".folders[] | select(.name == \"$client\") | .id")
    
    if [ -z "$FOLDER_ID" ] || [ "$FOLDER_ID" = "null" ]; then
        echo "   ⚠️  Folder nicht gefunden"
        continue
    fi
    
    echo "   ID: $FOLDER_ID"
    
    # Prüfe ob Creative Testing schon existiert
    echo "   🔍 Prüfe auf existierenden Folder..."
    EXISTING=$(echo "$FOLDERS" | jq -r ".folders[] | select(.name == \"Creative Testing\" and .id == \"$FOLDER_ID\") | .id")
    
    if [ -n "$EXISTING" ] && [ "$EXISTING" != "null" ]; then
        echo "   ⚠️  Existiert bereits"
        continue
    fi
    
    # Create Creative Testing folder
    echo "   🆕 Erstelle Folder..."
    CT_RESULT=$(make_request "POST" "https://api.clickup.com/api/v2/space/$SPACE_ID/folder" \
        "{\"name\":\"Creative Testing\",\"override_statuses\":true}")
    
    if echo "$CT_RESULT" | jq -e '.id' > /dev/null 2>&1; then
        CT_ID=$(echo "$CT_RESULT" | jq -r '.id')
        echo "   ✅ Folder: $CT_ID"
        
        # Create 3 Lists
        for list_name in "Creative Pipeline" "Creative Archive" "Creative Ideas"; do
            echo "      📝 Liste: $list_name..."
            LIST_RESULT=$(make_request "POST" "https://api.clickup.com/api/v2/folder/$CT_ID/list" \
                "{\"name\":\"$list_name\",\"content\":\"Auto-generated by Brain\"}")
            
            if echo "$LIST_RESULT" | jq -e '.id' > /dev/null 2>&1; then
                echo "      ✅ Erstellt"
            else
                ERR=$(echo "$LIST_RESULT" | jq -r '.err // .error // "Unknown"')
                echo "      ⚠️  $ERR"
            fi
        done
    else
        ERR=$(echo "$CT_RESULT" | jq -r '.err // .error // "Unknown"')
        echo "   ❌ Fehler: $ERR"
        echo "   Response: $CT_RESULT"
    fi
    
    echo ""
    echo "⏳ Warte 5 Sekunden vor nächstem Client..."
    sleep 5
    echo ""
done

echo "========================================="
echo "✅ Setup abgeschlossen!"
echo "Total Requests: $REQUEST_COUNT"
