#!/bin/bash
# Create ClickUp Dashboard for Outbound Campaign Performance

TOKEN="pk_63066979_9BJKQ4PHNOE3AEJWRH3PFKEH04MFZZY1"
SPACE_ID="90040244466"

echo "🎯 Creating Outbound Dashboard in ClickUp..."
echo ""

# Note: ClickUp Dashboard API is limited, so we'll create a comprehensive guide
# and try to create it via API

# Try to create dashboard
echo "📡 Attempting to create Dashboard via API..."

DASHBOARD=$(curl -s -X POST "https://api.clickup.com/api/v2/team/9006104573/dashboard" \
  -H "Authorization: ${TOKEN}" \
  -H "Content-Type: application/json" \
  -d '{
    "name": "📊 Outbound Performance Dashboard",
    "description": "Campaign performance tracking and hot leads overview"
  }')

DASHBOARD_ID=$(echo "$DASHBOARD" | jq -r '.id // empty')

if [[ -n "$DASHBOARD_ID" && "$DASHBOARD_ID" != "null" ]]; then
    echo "✅ Dashboard created: $DASHBOARD_ID"
    echo ""
    echo "🔗 Dashboard URL: https://app.clickup.com/9006104573/home/dashboards/$DASHBOARD_ID"
else
    echo "⚠️  Dashboard API limited - manual setup required"
    echo ""
fi

echo "═══════════════════════════════════════════════════════════════"
echo "📊 DASHBOARD SETUP GUIDE"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Da die ClickUp Dashboard API begrenzt ist, hier die Anleitung"
echo "für das manuelle Setup (5 Minuten):"
echo ""
echo "SCHRITT 1: Dashboard erstellen"
echo "─────────────────────────────────────────────────────────────"
echo "1. In ClickUp: Links im Menü auf 'Dashboards' klicken"
echo "2. '+ New Dashboard'"
echo "3. Name: '📊 Outbound Performance Dashboard'"
echo "4. 'Create'"
echo ""
echo "SCHRITT 2: Widgets hinzufügen"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "WIDGET 1: Active Campaigns Counter"
echo "• Klicke '+ Add Widget'"
echo "• Wähle: 'Number'"
echo "• Name: '📊 Active Campaigns'"
echo "• List: 'Campaign Overview'"
echo "• Filter: Status = 'Active'"
echo "• Anzeige: Count"
echo ""
echo "WIDGET 2: Total Emails Sent"
echo "• '+ Add Widget'"
echo "• Wähle: 'Number'"
echo "• Name: '📧 Emails Sent (This Week)'"
echo "• List: 'Campaign Overview'"
echo "• Custom Field: 'Sent Count'"
echo "• Anzeige: Sum"
echo ""
echo "WIDGET 3: Reply Rate Chart"
echo "• '+ Add Widget'"
echo "• Wähle: 'Bar Chart'"
echo "• Name: '📈 Reply Rate by Campaign'"
echo "• List: 'Campaign Overview'"
echo "• X-Achse: Campaign Name"
echo "• Y-Achse: Reply Rate %"
echo "• Filter: Status = 'Active'"
echo ""
echo "WIDGET 4: Hot Leads Pipeline"
echo "• '+ Add Widget'"
echo "• Wähle: 'Pie Chart'"
echo "• Name: '🔥 Hot Leads by Status'"
echo "• List: 'Hot Leads'"

sleep 2

echo "• Group by: 'Lead Status'"
echo "• Anzeige: Count"
echo ""
echo "WIDGET 5: Pipeline Value"
echo "• '+ Add Widget'"
echo "• Wähle: 'Number'"
echo "• Name: '💰 Total Pipeline Value'"
echo "• List: 'Hot Leads'"
echo "• Custom Field: 'Est. Deal Value'"
echo "• Filter: Status ≠ 'Closed Lost'"
echo "• Anzeige: Sum"
echo ""
echo "WIDGET 6: Recent Replies"
echo "• '+ Add Widget'"
echo "• Wähle: 'List'"
echo "• Name: '🚨 Recent Replies (Need Action)'"
echo "• List: 'Hot Leads'"
echo "• Filter: Lead Status = 'New Reply'"
echo "• Sort: Created Date (Neueste zuerst)"
echo "• Limit: 5"
echo ""
echo "WIDGET 7: Meetings This Week"
echo "• '+ Add Widget'"
echo "• Wähle: 'Number'"
echo "• Name: '📅 Meetings Booked'"
echo "• List: 'Hot Leads'"
echo "• Filter: Lead Status = 'Meeting Booked'"
echo "• Anzeige: Count"
echo ""
echo "WIDGET 8: Campaign Performance Table"
echo "• '+ Add Widget'"
echo "• Wähle: 'Table'"
echo "• Name: '📊 All Campaigns'"
echo "• List: 'Campaign Overview'"
echo "• Spalten: Campaign Name, Status, Leads, Sent, Replies, Reply Rate%, Meetings"
echo ""
echo "SCHRITT 3: Dashboard anordnen"
echo "─────────────────────────────────────────────────────────────"
echo "• Ziehe Widgets per Drag & Drop"
echo "• Mache wichtige Widgets größer"
echo "• Empfohlene Layout:"
echo ""
echo "  ┌─────────────────┬─────────────────┐"
echo "  │ Active Campaigns│ Emails Sent     │"
echo "  └─────────────────┴─────────────────┘"
echo "  ┌─────────────────┬─────────────────┐"
echo "  │ Reply Rate      │ Pipeline Value  │"
echo "  └─────────────────┴─────────────────┘"
echo "  ┌───────────────────────────────────┐"
echo "  │ Hot Leads by Status (Pie)         │"
echo "  └───────────────────────────────────┘"
echo "  ┌───────────────────────────────────┐"
echo "  │ 🚨 Recent Replies                 │"
echo "  └───────────────────────────────────┘"
echo "  ┌───────────────────────────────────┐"
echo "  │ All Campaigns Table               │"
echo "  └───────────────────────────────────┘"
echo ""
echo "SCHRITT 4: Sharing (Optional)"
echo "─────────────────────────────────────────────────────────────"
echo "• Oben rechts: 'Share'"
echo "• 'Private' → 'Shared with Team'"
echo "• Team Members hinzufügen"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "✅ DASHBOARD SETUP COMPLETE!"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "📱 Zugriff:"
echo "• Im Browser: https://app.clickup.com/9006104573/home/dashboards"
echo "• In der App: Sidebar → Dashboards → Outbound Performance"
echo ""
echo "🔄 Auto-Update:"
echo "• Alle Widgets aktualisieren sich automatisch alle 5 Min"
echo "• Oder: Manuell refresh mit '🔄' Button"
echo ""
echo "═══════════════════════════════════════════════════════════════"
