#!/bin/bash
# Weekly Outbound Report - Generates comprehensive weekly report
# Usage: ./weekly-outbound-report.sh
# Cron: 0 9 * * 1 (Monday 9am)

set -e

# Config
CLICKUP_KEY="${CLICKUP_API_TOKEN:-$(cat ~/.config/clickup/api_token 2>/dev/null || echo "")}"
CAMPAIGNS_LIST_ID="901521519128"
REPLY_LIST_ID="901521519132"
REPORT_FILE="/tmp/outbound_report_$(date +%Y-W%V).md"

if [[ -z "$CLICKUP_KEY" ]]; then
    echo "❌ Error: CLICKUP_API_TOKEN not set"
    exit 1
fi

WEEK=$(date +%V)
YEAR=$(date +%Y)
DATE_RANGE="$(date -v-7d +%d.%m) - $(date +%d.%m.%Y)"

echo "📊 Generating Weekly Outbound Report..."
echo "   Week: $YEAR-W$WEEK"
echo "   Period: $DATE_RANGE"
echo ""

# Initialize report
cat > "$REPORT_FILE" << EOF
# 📊 Outbound Report - KW $WEEK ($DATE_RANGE)

**Generated:** $(date '+%d.%m.%Y %H:%M')
**Status:** $(if [[ $(date +%u) -eq 1 ]]; then echo "🟢 Weekly Report"; else echo "🟡 Mid-Week Update"; fi)

---

## 📈 Campaign Performance

EOF

# Fetch campaigns
echo "📡 Analyzing campaigns..."

CAMPAIGNS=$(curl -s "https://api.clickup.com/api/v2/list/${CAMPAIGNS_LIST_ID}/task?include_closed=true" \
    -H "Authorization: ${CLICKUP_KEY}")

# Table header
cat >> "$REPORT_FILE" << EOF
| Campaign | Status | Leads | Reply Rate | Meeting Rate | Meetings |
|----------|--------|-------|------------|--------------|----------|
EOF

TOTAL_LEADS=0
TOTAL_REPLIES=0
TOTAL_MEETINGS=0

# Process campaigns
echo "$CAMPAIGNS" | jq -c '.tasks[]' | while read -r campaign; do
    NAME=$(echo "$campaign" | jq -r '.name' | cut -c1-25)
    STATUS=$(echo "$campaign" | jq -r '.status.status' | sed 's/to do/Draft/; s/complete/Completed/; s/open/Active/')
    LEADS=$(echo "$campaign" | jq -r '.custom_fields[] | select(.name=="Lead Count").value // 0')
    REPLY_RATE=$(echo "$campaign" | jq -r '.custom_fields[] | select(.name=="Reply Rate %").value // 0')
    MEETING_RATE=$(echo "$campaign" | jq -r '.custom_fields[] | select(.name=="Meeting Rate %").value // 0')
    
    # Calculate meetings (estimate)
    MEETINGS=$(echo "scale=0; ($LEADS * $MEETING_RATE) / 100" | bc 2>/dev/null || echo "0")
    
    # Status emoji
    case "$STATUS" in
        Active) STATUS_EMOJI="🟢" ;;
        Paused) STATUS_EMOJI="⏸️" ;;
        Draft) STATUS_EMOJI="📝" ;;
        Completed) STATUS_EMOJI="✅" ;;
        *) STATUS_EMOJI="⚪" ;;
    esac
    
    echo "| $NAME | $STATUS_EMOJI $STATUS | $LEADS | ${REPLY_RATE}% | ${MEETING_RATE}% | $MEETINGS |" >> "$REPORT_FILE"
    
    TOTAL_LEADS=$((TOTAL_LEADS + LEADS))
done

# Add totals
echo "" >> "$REPORT_FILE"
echo "**Totals:** $TOTAL_LEADS leads contacted | Reply rate varies | Meetings booked" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# Reply Analysis
cat >> "$REPORT_FILE" << EOF

## 💬 Reply Analysis

EOF

echo "📡 Analyzing replies..."

REPLIES=$(curl -s "https://api.clickup.com/api/v2/list/${REPLY_LIST_ID}/task?date_updated_gt=$(date -v-7d +%s)000" \
    -H "Authorization: ${CLICKUP_KEY}")

REPLY_COUNT=$(echo "$REPLIES" | jq -r '.tasks | length')

if [[ "$REPLY_COUNT" -gt 0 ]]; then
    cat >> "$REPORT_FILE" << EOF
| Type | Count | % |
|------|-------|---|
EOF
    
    # Count by type
    echo "$REPLIES" | jq -r '.tasks[].custom_fields[] | select(.name=="Reply Type").value' | sort | uniq -c | while read -r count type; do
        PERCENT=$(echo "scale=1; ($count / $REPLY_COUNT) * 100" | bc)
        EMOJI=$(case "$type" in
            Interested) echo "🔥" ;;
            Question) echo "❓" ;;
            "Not Interested") echo "❌" ;;
            OOO) echo "🏖️" ;;
            Referral) echo "🔗" ;;
            *) echo "💬" ;;
        esac)
        echo "| $EMOJI $type | $count | ${PERCENT}% |" >> "$REPORT_FILE"
    done
    
    echo "" >> "$REPORT_FILE"
    echo "**Total Replies:** $REPLY_COUNT" >> "$REPORT_FILE"
else
    echo "No replies recorded this week." >> "$REPORT_FILE"
fi

# Insights & Actions
cat >> "$REPORT_FILE" << EOF

---

## 🎯 Insights & Recommendations

### Top Performers
$(echo "$CAMPAIGNS" | jq -r '.tasks | sort_by(.custom_fields[] | select(.name=="Reply Rate %").value // 0) | reverse | .[0] | "- 🏆 \(.name): \(.custom_fields[] | select(.name=="Reply Rate %").value // 0)% reply rate"')

### Action Items
- [ ] Review low-performing campaigns (< 2% reply rate)
- [ ] Follow up on interested replies (🔥)
- [ ] Update sequences based on feedback
- [ ] Plan next week's outreach

---

## 📅 Next Week Focus

- [ ] Campaign: _______________
- [ ] Target: ___ new leads
- [ ] Sequence: _______________

---

*Report generated by Outbound Engine*
EOF

echo "✅ Report generated: $REPORT_FILE"
echo ""

# Display report
cat "$REPORT_FILE"

# Optional: Send to Slack/Email
# curl -X POST -H 'Content-type: application/json' \
#   --data "{\"text\":\"$(cat $REPORT_FILE)\"}" \
#   YOUR_SLACK_WEBHOOK

echo ""
echo "📤 Report saved to: $REPORT_FILE"
